server {
    listen 8080;

    location /api/notifications {
        proxy_pass http://notifications-svc-s11:8131/notifications;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://notifications-svc-s11:8131/health;
        proxy_set_header Host $host;
    }
}
