# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifications.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\x10notifications.v1\"L\n\x19\x43reateNotificationRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\"Y\n\x1a\x43reateNotificationResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"\x1a\n\x18ListNotificationsRequest\"O\n\x10NotificationItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"V\n\x19ListNotificationsResponse\x12\x39\n\rnotifications\x18\x01 \x03(\x0b\x32\".notifications.v1.NotificationItem2\xf5\x01\n\x14NotificationsService\x12o\n\x12\x43reateNotification\x12+.notifications.v1.CreateNotificationRequest\x1a,.notifications.v1.CreateNotificationResponse\x12l\n\x11ListNotifications\x12*.notifications.v1.ListNotificationsRequest\x1a+.notifications.v1.ListNotificationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_start=41
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_end=117
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_start=119
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_end=208
  _globals['_LISTNOTIFICATIONSREQUEST']._serialized_start=210
  _globals['_LISTNOTIFICATIONSREQUEST']._serialized_end=236
  _globals['_NOTIFICATIONITEM']._serialized_start=238
  _globals['_NOTIFICATIONITEM']._serialized_end=317
  _globals['_LISTNOTIFICATIONSRESPONSE']._serialized_start=319
  _globals['_LISTNOTIFICATIONSRESPONSE']._serialized_end=405
  _globals['_NOTIFICATIONSSERVICE']._serialized_start=408
  _globals['_NOTIFICATIONSSERVICE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
